export const ProjectData = [
  {
    projectName: "Project Alpha (Core Portal)",
    color: "#0284c7",
    status: "ACTIVE",
    assignedCount: "5 members",
    projectTeamMembers: ["AR", "VM", "MC", "LO", "DM"],
    totalTasks: "6 tasks",
  },
  {
    projectName: "Project Beta (Design System)",
    color: "#dc2626",
    status: "ACTIVE",
    assignedCount: "4 members",
    projectTeamMembers: ["AR", "ER", "SW", "JO"],
    totalTasks: "5 tasks",
  },
  {
    projectName: "Project Gamma (Mobile App)",
    color: "#16a34a",
    status: "ACTIVE",
    assignedCount: "6 members",
    projectTeamMembers: ["AR", "VM", "DM", "SW", "PS", "CM"],
    totalTasks: "4 tasks",
  },
  {
    projectName: "Internal R&D / Ops",
    color: "#a16207",
    status: "ACTIVE",
    assignedCount: "8 members",
    projectTeamMembers: ["SJ", "AR", "VM", "MC", "ER", "LO", "+2"],
    totalTasks: "3 tasks",
  },
  {
    projectName: "Project Delta (AI Analytics)",
    color: "#7c3aed",
    status: "ACTIVE",
    assignedCount: "4 members",
    projectTeamMembers: ["PS", "CM", "RA", "TN"],
    totalTasks: "3 tasks",
  },
  {
    projectName: "Project Epsilon (Cloud Migration)",
    color: "#ea580c",
    status: "ACTIVE",
    assignedCount: "5 members",
    projectTeamMembers: ["AR", "VM", "MC", "DM", "TN"],
    totalTasks: "4 tasks",
  },
  {
    projectName: "Project Zeta (E-Commerce Revamp)",
    color: "#10b981",
    status: "ON HOLD",
    assignedCount: "5 members",
    projectTeamMembers: ["ER", "JO", "AN", "RA", "FZ"],
    totalTasks: "2 tasks",
  },
];