--
-- PostgreSQL database dump
--

\restrict WMyHwOKUUjVjRaiBxWR4TXlcRChzgaKoabbSlSe81zwDDlbUuzmpsojgZljfpfa

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attachments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attachments (
    id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    file_path character varying(500) NOT NULL,
    file_size_bytes bigint NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    uploaded_by bigint NOT NULL,
    meeting_id bigint NOT NULL
);


ALTER TABLE public.attachments OWNER TO postgres;

--
-- Name: attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    entity_id bigint NOT NULL,
    entity_type character varying(255) NOT NULL,
    ip_address character varying(255),
    new_value jsonb,
    old_value jsonb,
    "timestamp" timestamp(6) without time zone NOT NULL,
    user_agent character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.audit_logs OWNER TO postgres;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: components; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.components (
    id bigint NOT NULL,
    component_key character varying(255) NOT NULL,
    component_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    icon character varying(255),
    is_active boolean NOT NULL,
    portal character varying(255) NOT NULL,
    route_path character varying(255) NOT NULL,
    parent_component_id bigint
);


ALTER TABLE public.components OWNER TO postgres;

--
-- Name: components_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.components ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.components_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by bigint,
    delete_reason character varying(255),
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    is_deleted boolean NOT NULL,
    designation character varying(255) NOT NULL,
    employee_code character varying(255) NOT NULL,
    joining_date date NOT NULL,
    name character varying(255) NOT NULL,
    notification_preference character varying(255) NOT NULL,
    personal_email character varying(255),
    phone character varying(255) NOT NULL,
    profile_image character varying(255),
    status character varying(255) NOT NULL,
    work_email character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT employees_check CHECK ((((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'ON_LEAVE'::character varying])::text[])) AND ((notification_preference)::text = ANY ((ARRAY['EMAIL'::character varying, 'WHATSAPP'::character varying, 'TEAMS'::character varying, 'ALL'::character varying])::text[]))))
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eta_extension_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eta_extension_requests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    new_eta_date date NOT NULL,
    old_eta_date date NOT NULL,
    reason text NOT NULL,
    rejection_reason text,
    reviewed_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    requested_by bigint NOT NULL,
    reviewed_by bigint,
    task_id bigint NOT NULL,
    CONSTRAINT eta_extension_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.eta_extension_requests OWNER TO postgres;

--
-- Name: eta_extension_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eta_extension_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eta_extension_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.feed (
    id bigint NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    publish_to_internal boolean NOT NULL,
    publish_to_teams boolean NOT NULL,
    severity character varying(255) NOT NULL,
    teams_message_id character varying(255),
    teams_post_status character varying(255),
    title character varying(255) NOT NULL,
    created_by bigint NOT NULL,
    CONSTRAINT feed_check CHECK ((((severity)::text = ANY ((ARRAY['INFO'::character varying, 'WARNING'::character varying, 'CRITICAL'::character varying, 'SUCCESS'::character varying])::text[])) AND ((teams_post_status IS NULL) OR ((teams_post_status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))))
);


ALTER TABLE public.feed OWNER TO postgres;

--
-- Name: feed_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.feed ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feed_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: links; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.links (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by bigint,
    filelink character varying(255) NOT NULL,
    filename character varying(255) NOT NULL
);


ALTER TABLE public.links OWNER TO postgres;

--
-- Name: links_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_attendees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meeting_attendees (
    meeting_id bigint NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.meeting_attendees OWNER TO postgres;

--
-- Name: meetings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meetings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by bigint,
    description text,
    duration_minutes integer NOT NULL,
    meeting_link character varying(255) NOT NULL,
    start_time timestamp(6) without time zone NOT NULL,
    title character varying(255) NOT NULL,
    project_id bigint,
    task_id bigint
);


ALTER TABLE public.meetings OWNER TO postgres;

--
-- Name: meetings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.meetings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meetings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    is_used boolean NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.password_reset_tokens OWNER TO postgres;

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissions (
    id bigint NOT NULL,
    description character varying(255),
    permission_name character varying(255) NOT NULL
);


ALTER TABLE public.permissions OWNER TO postgres;

--
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_members (
    id bigint NOT NULL,
    employee_id bigint NOT NULL,
    project_id bigint NOT NULL
);


ALTER TABLE public.project_members OWNER TO postgres;

--
-- Name: project_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_milestones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_milestones (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    due_date date NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    project_id bigint NOT NULL,
    CONSTRAINT project_milestones_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'MISSED'::character varying])::text[])))
);


ALTER TABLE public.project_milestones OWNER TO postgres;

--
-- Name: project_milestones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_milestones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_milestones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_teams (
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    team_id bigint NOT NULL
);


ALTER TABLE public.project_teams OWNER TO postgres;

--
-- Name: project_teams_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by bigint,
    delete_reason character varying(255),
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    is_deleted boolean NOT NULL,
    client_name character varying(255) NOT NULL,
    color_hex character varying(7) NOT NULL,
    description character varying(255),
    end_date date,
    progress_percentage integer NOT NULL,
    project_name character varying(255) NOT NULL,
    start_date date NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT projects_check CHECK ((((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ON_HOLD'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])) AND (progress_percentage >= 0) AND (progress_percentage <= 100) AND ((color_hex)::text ~ '^#[A-Fa-f0-9]{6}$'::text))),
    CONSTRAINT projects_progress_percentage_check CHECK (((progress_percentage <= 100) AND (progress_percentage >= 0)))
);


ALTER TABLE public.projects OWNER TO postgres;

--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    device_info character varying(255),
    expires_at timestamp(6) without time zone NOT NULL,
    is_revoked boolean NOT NULL,
    token character varying(512) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.refresh_tokens OWNER TO postgres;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_components; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_components (
    id bigint NOT NULL,
    can_create boolean NOT NULL,
    can_delete boolean NOT NULL,
    can_edit boolean NOT NULL,
    can_view boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    component_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.role_components OWNER TO postgres;

--
-- Name: role_components_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role_components ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_components_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permissions (
    id bigint NOT NULL,
    permission_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.role_permissions OWNER TO postgres;

--
-- Name: role_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    role_code character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_attachments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_attachments (
    id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    file_path character varying(500) NOT NULL,
    file_size_bytes bigint NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    task_id bigint NOT NULL,
    uploaded_by bigint NOT NULL
);


ALTER TABLE public.task_attachments OWNER TO postgres;

--
-- Name: task_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_comments (
    id bigint NOT NULL,
    comment_text text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    author_id bigint NOT NULL,
    task_id bigint NOT NULL
);


ALTER TABLE public.task_comments OWNER TO postgres;

--
-- Name: task_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_progress (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    notes text,
    progress_percentage integer NOT NULL,
    employee_id bigint NOT NULL,
    task_id bigint NOT NULL,
    CONSTRAINT task_progress_progress_percentage_check CHECK (((progress_percentage <= 100) AND (progress_percentage >= 0)))
);


ALTER TABLE public.task_progress OWNER TO postgres;

--
-- Name: task_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_status_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_status_history (
    id bigint NOT NULL,
    changed_at timestamp(6) without time zone NOT NULL,
    new_status character varying(255) NOT NULL,
    old_status character varying(255) NOT NULL,
    reason text,
    changed_by bigint,
    task_id bigint NOT NULL
);


ALTER TABLE public.task_status_history OWNER TO postgres;

--
-- Name: task_status_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_status_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_status_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_tag_mapping; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_tag_mapping (
    id bigint NOT NULL,
    tag_id bigint NOT NULL,
    task_id bigint NOT NULL
);


ALTER TABLE public.task_tag_mapping OWNER TO postgres;

--
-- Name: task_tag_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_tag_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_tag_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_tags (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    tag_name character varying(255) NOT NULL
);


ALTER TABLE public.task_tags OWNER TO postgres;

--
-- Name: task_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_transfer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_transfer (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    reason text NOT NULL,
    rejection_reason text,
    reviewed_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    requested_by bigint NOT NULL,
    reviewed_by bigint,
    target_employee_id bigint NOT NULL,
    task_id bigint NOT NULL,
    CONSTRAINT task_transfer_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.task_transfer OWNER TO postgres;

--
-- Name: task_transfer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_transfer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_transfer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by bigint,
    delete_reason character varying(255),
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    is_deleted boolean NOT NULL,
    bug_number character varying(255),
    description character varying(255),
    epic character varying(255),
    eta_date date NOT NULL,
    eta_hours numeric(38,2) NOT NULL,
    extended_eta_date date,
    original_eta_date date NOT NULL,
    priority character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    task_number character varying(255) NOT NULL,
    task_type character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    assigned_to bigint,
    project_id bigint NOT NULL,
    completion_review_status character varying(255),
    justification text,
    logged_hours numeric(38,2),
    review_comment text,
    CONSTRAINT tasks_check CHECK ((((task_type)::text = ANY ((ARRAY['FEATURE'::character varying, 'BUG'::character varying, 'STORY'::character varying, 'RND'::character varying, 'CRC'::character varying, 'COC'::character varying, 'SUPPORT'::character varying, 'TASK'::character varying, 'POC'::character varying])::text[])) AND ((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[])) AND ((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'PENDING_REVIEW'::character varying, 'COMPLETED'::character varying, 'OVER_ETA'::character varying, 'TRANSFERRED'::character varying, 'ETA_EXTENDED'::character varying, 'REJECTED'::character varying])::text[]))))
);


ALTER TABLE public.tasks OWNER TO postgres;

--
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.team_members (
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    employee_id bigint NOT NULL,
    team_id bigint NOT NULL
);


ALTER TABLE public.team_members OWNER TO postgres;

--
-- Name: team_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.team_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teams (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by bigint,
    delete_reason character varying(255),
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    is_deleted boolean NOT NULL,
    description character varying(255),
    status character varying(255) NOT NULL,
    team_name character varying(255) NOT NULL,
    teams_channel_id character varying(255),
    lead_id bigint,
    sub_lead_id bigint,
    CONSTRAINT teams_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.teams OWNER TO postgres;

--
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timesheet_entries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.timesheet_entries (
    id bigint NOT NULL,
    approved_at timestamp(6) without time zone,
    bug_number character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    description text NOT NULL,
    end_time timestamp(6) without time zone NOT NULL,
    hours_spent numeric(4,2) NOT NULL,
    justification text,
    manager_comment text,
    start_time timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    work_category character varying(255) NOT NULL,
    work_date date NOT NULL,
    approved_by bigint,
    employee_id bigint NOT NULL,
    project_id bigint,
    task_id bigint,
    CONSTRAINT timesheet_entries_check CHECK ((((work_category)::text = ANY ((ARRAY['FEATURE'::character varying, 'BUG'::character varying, 'STORY'::character varying, 'R&D'::character varying, 'CRC'::character varying, 'COC'::character varying, 'SUPPORT'::character varying, 'TASK'::character varying, 'OTHER'::character varying, 'MEETING'::character varying, 'ADMIN'::character varying, 'REVIEW'::character varying, 'GENERAL'::character varying, 'BREAK'::character varying])::text[])) AND ((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[]))))
);


ALTER TABLE public.timesheet_entries OWNER TO postgres;

--
-- Name: timesheet_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.timesheet_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timesheet_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    id bigint NOT NULL,
    assigned_at timestamp(6) without time zone NOT NULL,
    assigned_by bigint,
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Name: user_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    account_locked_until timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    failed_login_attempts integer NOT NULL,
    force_password_change boolean NOT NULL,
    is_active boolean NOT NULL,
    last_login timestamp(6) without time zone,
    password_hash character varying(255) NOT NULL,
    password_last_updated_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: attachments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attachments (id, file_name, file_path, file_size_bytes, uploaded_at, uploaded_by, meeting_id) FROM stdin;
\.


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audit_logs (id, action, entity_id, entity_type, ip_address, new_value, old_value, "timestamp", user_agent, user_id) FROM stdin;
\.


--
-- Data for Name: components; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.components (id, component_key, component_name, created_at, display_order, icon, is_active, portal, route_path, parent_component_id) FROM stdin;
1	DASHBOARD	Dashboard	2026-06-16 18:09:38.020586	1	layout-dashboard	t	SHARED	/dashboard	\N
2	ADMIN_OVERVIEW	Admin Overview	2026-06-16 18:09:38.026585	2	shield-alert	t	ADMIN	/admin/overview	\N
3	TIMESHEET_SUBMIT	Timesheets	2026-06-16 18:09:38.03159	3	clock	t	SHARED	/timesheets	\N
4	MEETINGS_VIEW	Link Room	2026-06-16 18:09:38.035094	4	video	t	SHARED	/meetings	\N
5	EMPLOYEES	Employees Directory	2026-06-16 18:09:38.040133	5	users	t	ADMIN	/admin/employees	\N
\.


--
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employees (id, created_at, created_by, updated_at, updated_by, delete_reason, deleted_at, deleted_by, is_deleted, designation, employee_code, joining_date, name, notification_preference, personal_email, phone, profile_image, status, work_email, user_id) FROM stdin;
1	2026-06-16 18:09:37.781579	\N	2026-06-16 18:09:37.781579	\N	\N	\N	\N	f	Administrator	EMP-001	2026-06-16	Admin User	ALL	\N	0000000000	\N	ACTIVE	admin@teamops.com	1
4	2026-06-16 18:14:45.322553	1	2026-06-16 18:36:18.68698	3	"Removed by admin"	2026-06-16 18:36:18.686088	3	t	Intern	INT-002	2026-06-16	Aki	ALL	aki@gmail.com	6969696969		INACTIVE	aki@gmail.com	4
5	2026-06-16 18:16:01.080763	1	2026-06-17 16:39:55.159079	1	\N	\N	\N	f	Intern	INT-002	2026-06-16	Ritesh	ALL	ritesh@gmail.com	9966226123		ACTIVE	ritesh@gmail.com	5
7	2026-06-17 11:27:02.229732	1	2026-06-17 15:08:07.260177	1	"Removed by admin"	2026-06-17 15:08:07.248652	1	t	Employee	EMQIJWej-0010101	2026-06-17	rithvik saravanan	ALL	rithvikradasdhika@gmail.com	+919962060368123		INACTIVE	rithvasdasdikradhika@gmail.com	7
6	2026-06-16 18:16:55.94141	1	2026-06-17 15:08:36.084882	1	"Removed by admin"	2026-06-17 15:08:36.079964	1	t	Intern	INT-004	2026-06-17	Sundar	ALL	ritasdesh@gmail.com	827263547123		INACTIVE	ritasdesh@gmail.com	6
8	2026-06-17 14:48:40.325326	1	2026-06-17 15:11:51.275973	1	"Removed by admin"	2026-06-17 15:11:51.274363	1	t	test dummy	1	2026-06-17	1	ALL	emp@emp.com	9989889988		INACTIVE	emp@emp.com	8
9	2026-06-17 14:49:05.340698	1	2026-06-17 15:11:53.308612	1	"Removed by admin"	2026-06-17 15:11:53.308612	1	t	test dummy	2	2026-06-17	2	ALL	emp2@emp.com	11221		INACTIVE	emp2@emp.com	9
10	2026-06-17 14:49:29.430202	1	2026-06-17 15:11:56.229066	1	"Removed by admin"	2026-06-17 15:11:56.225901	1	t	test dummy	3	2026-06-17	3	ALL	rithvikradhika@gmail.com	+9199620603681231		INACTIVE	emp3@emp.com	10
2	2026-06-16 18:09:37.892467	\N	2026-06-17 15:11:58.839314	1	"Removed by admin"	2026-06-17 15:11:58.836929	1	t	Software Engineer	EMP-002	2026-06-16	Employee User	ALL	\N	1111111111	\N	INACTIVE	employee@teamops.com	2
13	2026-06-17 15:20:37.163024	1	2026-06-17 15:20:47.039838	1	\N	\N	\N	f	UI Developer	EMP-004	2026-06-17	Karuppasamy	ALL	Karuppasamy@elitecorpusa.com	962060368		ACTIVE	Karuppasamy@elitecorpusa.com	13
14	2026-06-17 15:25:08.5732	1	2026-06-17 15:25:08.5732	1	\N	\N	\N	f	IOS Developer	EMP-005	2026-06-17	MD Iqbal A	ALL	MDIqbalA@elitecorpusa.com	9162060368		ACTIVE	MDIqbalA@elitecorpusa.com	14
15	2026-06-17 15:25:53.092815	1	2026-06-17 15:25:53.092815	1	\N	\N	\N	f	Human Resource	EMP-006	2026-06-17	Jegan Rajendran	ALL	JeganRajendran@elitecorpusa.com	919962060368		ACTIVE	JeganRajendran@elitecorpusa.com	15
16	2026-06-17 15:27:05.97035	1	2026-06-17 15:27:05.97035	1	\N	\N	\N	f	Senior Frontend Dev	EMP-007	2026-06-17	Richard Mathew	ALL	RichardMathew@elitecorpusa.com	8962060368		ACTIVE	RichardMathew@elitecorpusa.com	16
17	2026-06-17 15:28:34.835006	1	2026-06-17 15:28:34.835006	1	\N	\N	\N	f	Frontend	EMP-008	2026-06-17	Balamurugan Ravi	ALL	rithvikradhika@gmail.com	+91996206036		ACTIVE	BalamuruganRavi@elitecorpusa.com	17
21	2026-06-17 16:09:06.806744	\N	2026-06-17 16:09:06.806744	\N	\N	\N	\N	f	Software Engineer	EMP-002	2026-06-17	Employee User	ALL	\N	1111111111	\N	ACTIVE	employee@teamops.com	2
22	2026-06-17 16:12:59.769272	1	2026-06-17 16:13:06.539946	1	"Removed by admin"	2026-06-17 16:13:06.537862	1	t	qweqweq	EMP-009	2026-06-17	rithvik saravanan	ALL	rithvikradhika@gmail.com	+919962060368		INACTIVE	admin@teamops.comqweqw	20
23	2026-06-17 16:13:19.613572	1	2026-06-17 16:17:36.015215	1	"Removed by admin"	2026-06-17 16:17:36.013677	1	t	qweqweqwe	EMP-009	2026-06-17	rithvik saravanan	ALL	rithvikradhika@gmail.com	+919962060368		INACTIVE	admin@teamops.comasdqwe	21
24	2026-06-17 16:24:57.083	1	2026-06-17 16:24:57.083	1	\N	\N	\N	f	Project Manager	EMP-009	2026-06-17	 Purushothaman Saminathan	ALL	spurushothaman@elitecorpusa.com	9792226885		ACTIVE	spurushothaman@elitecorpusa.com	25
3	2026-06-16 18:13:44.984887	1	2026-06-17 16:39:18.783096	1	\N	\N	\N	f	Intern	INT-001	2026-06-16	rithvik saravanan	ALL	rithvikradhaika@gmail.com	962060366		ACTIVE	rithvikradhika@gmail.com	3
25	2026-06-17 16:40:33.917267	1	2026-06-17 16:40:33.917267	1	\N	\N	\N	f	Intern	INT-003	2026-06-17	Akhilesh	ALL	Akhilesh@gmail.com	998771266		ACTIVE	Akhilesh@gmail.com	26
26	2026-06-18 12:21:47.248826	1	2026-06-18 12:21:47.248826	1	\N	\N	\N	f	WTRerd	EMP-010	2026-06-18	rithvik saravanan	ALL	wqert@qwe.com	+919962060368887		ACTIVE	wqert@qwe.com	27
12	2026-06-17 15:19:47.142874	1	2026-06-18 16:23:13.3555	25	\N	\N	\N	f	UI-UX	EMP-003	2026-06-18	Yogeswaran	ALL	yogeshwaran@elitecorpusa.com	996206036		ACTIVE	yogeshwaran@elitecorpusa.com	12
\.


--
-- Data for Name: eta_extension_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.eta_extension_requests (id, created_at, new_eta_date, old_eta_date, reason, rejection_reason, reviewed_at, status, requested_by, reviewed_by, task_id) FROM stdin;
1	2026-06-26 11:57:20.277634	2026-06-27	2026-06-18	jwdbsljdnsla	\N	\N	PENDING	3	\N	6
\.


--
-- Data for Name: feed; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.feed (id, content, created_at, publish_to_internal, publish_to_teams, severity, teams_message_id, teams_post_status, title, created_by) FROM stdin;
1	hello	2026-06-25 16:49:54.346701	t	f	WARNING	\N	\N	hi	1
\.


--
-- Data for Name: links; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.links (id, created_at, created_by, updated_at, updated_by, filelink, filename) FROM stdin;
1	2026-06-26 10:54:54.940509	1	2026-06-26 10:54:54.940509	1	https://github.com/ritesh-prajan/Employee-Resource-Manager	test
\.


--
-- Data for Name: meeting_attendees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.meeting_attendees (meeting_id, employee_id) FROM stdin;
\.


--
-- Data for Name: meetings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.meetings (id, created_at, created_by, updated_at, updated_by, description, duration_minutes, meeting_link, start_time, title, project_id, task_id) FROM stdin;
\.


--
-- Data for Name: password_reset_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_reset_tokens (id, created_at, expires_at, is_used, token, user_id) FROM stdin;
\.


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.permissions (id, description, permission_name) FROM stdin;
1	Create system user credentials	USER_CREATE
2	Onboard and edit employee profiles	EMPLOYEE_MANAGE
3	Create task tickets	TASK_CREATE
4	View task tickets	TASK_VIEW
5	Assign tasks to employees	TASK_ASSIGN
6	Approve and reject timesheets	TIMESHEET_APPROVE
7	Submit weekly timesheets	TIMESHEET_SUBMIT
8	Create teams and assign/manage members	TEAM_MANAGE
9	Create projects and assign/manage members	PROJECT_MANAGE
10	View system user accounts	USER_VIEW
11	Update system user accounts	USER_UPDATE
12	Delete system user accounts	USER_DELETE
13	View employee records	EMPLOYEE_VIEW
14	Create employee records	EMPLOYEE_CREATE
15	Update employee records	EMPLOYEE_UPDATE
16	Delete employee records	EMPLOYEE_DELETE
17	View team records	TEAM_VIEW
18	Create teams	TEAM_CREATE
19	Update team details	TEAM_UPDATE
20	Delete teams	TEAM_DELETE
21	View project records	PROJECT_VIEW
22	Create projects	PROJECT_CREATE
23	Update project details	PROJECT_UPDATE
24	Delete projects	PROJECT_DELETE
25	Update task details	TASK_UPDATE
26	Delete tasks	TASK_DELETE
27	View timesheet entries	TIMESHEET_VIEW
28	Create timesheet entries	TIMESHEET_CREATE
29	Update timesheet entries	TIMESHEET_UPDATE
30	Delete timesheet entries	TIMESHEET_DELETE
31	View attachments	ATTACHMENT_VIEW
32	Upload attachments	ATTACHMENT_UPLOAD
33	Delete attachments	ATTACHMENT_DELETE
34	View announcements	ANNOUNCEMENT_VIEW
35	Create announcements	ANNOUNCEMENT_CREATE
36	Update announcements	ANNOUNCEMENT_UPDATE
37	Delete announcements	ANNOUNCEMENT_DELETE
38	Post messages to Microsoft Teams	TEAMS_POST
39	View meeting details and schedules	MEETING_VIEW
40	Schedule new meetings	MEETING_CREATE
41	Update scheduled meetings	MEETING_UPDATE
42	Cancel or delete meetings	MEETING_DELETE
43	View links	LINK_VIEW
44	Create links	LINK_CREATE
45	Update links	LINK_UPDATE
46	Delete links	LINK_DELETE
\.


--
-- Data for Name: project_members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.project_members (id, employee_id, project_id) FROM stdin;
8	12	4
9	13	4
10	14	4
11	15	4
12	16	4
13	24	5
14	17	5
15	16	5
16	15	5
17	14	5
18	3	3
19	5	3
20	25	3
27	12	3
28	12	5
29	1	7
30	13	7
31	25	7
32	3	7
33	26	7
34	24	7
35	12	7
36	1	8
37	17	8
38	21	8
39	3	8
40	25	8
41	26	8
\.


--
-- Data for Name: project_milestones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.project_milestones (id, completed_at, due_date, status, title, project_id) FROM stdin;
\.


--
-- Data for Name: project_teams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.project_teams (id, project_id, team_id) FROM stdin;
\.


--
-- Data for Name: projects; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.projects (id, created_at, created_by, updated_at, updated_by, delete_reason, deleted_at, deleted_by, is_deleted, client_name, color_hex, description, end_date, progress_percentage, project_name, start_date, status) FROM stdin;
1	2026-06-16 18:41:04.927984	3	2026-06-16 18:45:12.338934	3	"Removed by admin"	2026-06-16 18:45:12.338934	3	t	Elite Software Solutions	#8a05d1		2026-06-30	0	Elite Website 	2026-05-20	CANCELLED
2	2026-06-16 18:45:49.339168	3	2026-06-16 18:48:39.654711	3	"Removed by admin"	2026-06-16 18:48:39.654711	3	t	Elite Software Solutions	#7505d1		2026-06-30	0	Elite Web	2026-05-20	CANCELLED
3	2026-06-16 18:49:27.448671	3	2026-06-17 13:22:29.094118	1	\N	\N	\N	f	Elite Software Solution	#2087b6		\N	0	Elite Web	2026-06-16	ACTIVE
4	2026-06-17 16:30:10.568399	1	2026-06-17 16:30:10.568399	1	\N	\N	\N	f	alliance of audited media	#F5958E		\N	0	AAM	2022-05-20	ACTIVE
5	2026-06-17 16:31:01.67116	1	2026-06-17 16:31:01.67116	1	\N	\N	\N	f	Calix	#8ECAE6		\N	0	Calix Cloud	2025-05-17	ACTIVE
6	2026-06-18 13:02:52.896231	16	2026-06-18 16:58:14.591595	1	"Removed by admin"	2026-06-18 16:58:14.57945	1	t	Redbull	#8ECAE6		\N	0	Formula car design	2026-06-18	CANCELLED
7	2026-06-18 17:03:03.312731	1	2026-06-18 17:03:03.312731	1	\N	\N	\N	f	SMX-Calix	#8ECAE6		\N	0	SMX	2024-07-18	ACTIVE
8	2026-06-26 11:43:26.064138	1	2026-06-26 11:43:26.064138	1	\N	\N	\N	f	test	#8ECAE6		2027-06-26	0	test	2026-06-26	ACTIVE
\.


--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.refresh_tokens (id, created_at, device_info, expires_at, is_revoked, token, user_id) FROM stdin;
3	2026-06-16 18:27:00.881295	\N	2026-06-24 15:13:43.808331	f	07e204d1-b56f-43d2-8c7e-4eaf2a78f5d8	5
8	2026-06-18 12:17:55.420928	\N	2026-06-18 19:23:33.845652	f	de8145ec-f8a8-4683-af79-fb7f9530e6a8	12
6	2026-06-17 16:09:53.630728	\N	2026-06-18 19:46:47.393068	f	49596c7c-96bc-4f1e-a8fe-aa1a7d2c64bb	17
11	2026-06-18 16:37:43.889774	\N	2026-06-18 19:55:06.589552	f	f0b000b4-3988-4ba5-b53a-62d2b459343d	13
2	2026-06-16 18:17:09.059504	\N	2026-06-17 17:46:58.244161	f	b050c925-ced8-424c-b499-19a00c7c8f77	6
5	2026-06-17 11:31:06.743182	\N	2026-06-17 17:47:16.794636	f	9e9ba8c4-6af2-44bb-bc29-e05108dc8b4d	7
4	2026-06-16 18:32:45.697423	\N	2026-06-26 14:56:18.421455	f	65946b5e-35b1-4d09-8689-09704a1c9bde	3
9	2026-06-18 12:18:18.866922	\N	2026-06-22 20:11:54.234307	f	518d9498-0ae8-48e5-b731-d58bc48fa964	16
7	2026-06-18 11:47:21.405064	\N	2026-06-22 20:13:19.799767	f	a536354a-9cd4-4d1d-bf56-ce17688d7d93	25
1	2026-06-16 18:09:47.265284	\N	2026-06-26 18:38:52.398731	f	1665bcac-5eb9-48fa-84f8-aa3888c916cc	1
10	2026-06-18 12:21:51.462016	\N	2026-06-18 15:22:19.467133	f	685c2bd7-4cd9-4729-ba62-d3319dc451bf	27
12	2026-06-22 16:16:21.231339	\N	2026-06-23 19:43:43.417065	f	da7cac07-e416-4024-b528-9b0031c78da1	26
\.


--
-- Data for Name: role_components; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role_components (id, can_create, can_delete, can_edit, can_view, created_at, component_id, role_id) FROM stdin;
1	t	t	t	t	2026-06-16 18:09:38.053761	1	1
2	t	t	t	t	2026-06-16 18:09:38.063273	2	1
3	t	t	t	t	2026-06-16 18:09:38.070924	3	1
4	t	t	t	t	2026-06-16 18:09:38.078922	4	1
5	t	t	t	t	2026-06-16 18:09:38.085439	5	1
6	t	t	t	t	2026-06-16 18:09:38.09344	1	2
7	t	t	t	t	2026-06-16 18:09:38.09995	3	2
8	t	t	t	t	2026-06-16 18:09:38.106494	4	2
9	f	f	f	t	2026-06-16 18:09:38.111626	1	4
10	t	f	t	t	2026-06-16 18:09:38.115768	3	4
11	f	f	f	t	2026-06-16 18:09:38.118798	4	4
\.


--
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role_permissions (id, permission_id, role_id) FROM stdin;
1	1	1
2	2	1
3	3	1
4	4	1
5	5	1
6	6	1
7	7	1
8	8	1
9	9	1
10	3	2
11	4	2
12	5	2
13	6	2
14	7	2
15	8	2
16	9	2
17	7	4
18	10	1
19	11	1
20	12	1
21	13	1
22	14	1
23	15	1
24	16	1
25	17	1
26	18	1
27	19	1
28	20	1
29	21	1
30	22	1
31	23	1
32	24	1
33	25	1
34	26	1
35	13	2
36	17	2
37	19	2
38	21	2
39	22	2
40	23	2
41	25	2
42	26	2
43	13	3
44	17	3
45	19	3
46	21	3
47	22	3
48	23	3
49	4	3
50	3	3
51	25	3
52	26	3
53	13	4
54	17	4
55	21	4
56	4	4
57	18	2
58	20	2
59	24	2
60	18	3
61	20	3
62	24	3
63	27	1
64	28	1
65	29	1
66	30	1
67	27	2
68	28	2
69	29	2
70	30	2
71	27	3
72	28	3
73	29	3
74	30	3
75	27	4
76	28	4
77	30	4
78	31	1
79	32	1
80	33	1
81	34	1
82	35	1
83	36	1
84	37	1
85	38	1
86	31	2
87	32	2
88	33	2
89	34	2
90	35	2
91	36	2
92	37	2
93	38	2
94	31	3
95	32	3
96	33	3
97	34	3
98	35	3
99	36	3
100	37	3
101	38	3
102	31	4
103	32	4
104	33	4
105	34	4
106	38	4
107	39	1
108	40	1
109	41	1
110	42	1
111	39	2
112	40	2
113	41	2
114	42	2
115	39	3
116	40	3
117	41	3
118	42	3
119	39	4
120	40	4
121	41	4
122	42	4
123	43	1
124	44	1
125	45	1
126	46	1
127	43	2
128	44	2
129	45	2
130	46	2
131	43	3
132	44	3
133	45	3
134	46	3
135	43	4
136	44	4
137	45	4
138	46	4
139	25	4
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, created_at, description, is_active, name, role_code) FROM stdin;
1	2026-06-16 18:09:37.608842	Read-everything watchdog. Creates employees, teams, projects. Gets alert flags for anomalies.	t	Admin	ADMIN
2	2026-06-16 18:09:37.65887	Full operational control. Creates and assigns tasks. Approves timesheets and ETA extensions.	t	Team Lead	TEAM_LEAD
3	2026-06-16 18:09:37.661721	Same as TEAM_LEAD with limited override permissions. Stored as a role tag.	t	Sub Lead	SUB_LEAD
4	2026-06-16 18:09:37.662722	Clocks in/out, logs hours, updates task progress, requests ETA extensions and reassignments.	t	Employee	EMPLOYEE
\.


--
-- Data for Name: task_attachments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_attachments (id, file_name, file_path, file_size_bytes, uploaded_at, task_id, uploaded_by) FROM stdin;
\.


--
-- Data for Name: task_comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_comments (id, comment_text, created_at, author_id, task_id) FROM stdin;
44	[Submitted for Review - Comment]: nkansla	2026-06-26 06:07:20.463	3	5
45	[Started task tracking]	2026-06-26 06:07:30.121	3	5
46	[Submitted for Review - Comment]: nkansla	2026-06-26 06:07:37.888	3	5
47	[Submitted for Review - Comment]: nkansla	2026-06-26 06:07:43.906	3	5
48	[Paused]. Session hours: 0h.	2026-06-26 06:17:15.314	3	5
49	[Logged Time - Comment]: dasds. Session hours: 1h.	2026-06-26 06:17:32.19	3	6
50	[Logged Time - Comment]: sdasd. Session hours: 2h.	2026-06-26 06:18:20.025	3	6
51	[Started task tracking]	2026-06-26 06:26:52.042	3	6
52	[Paused]. Session hours: 0h.	2026-06-26 06:27:01.708	3	6
53	k ,	2026-06-26 06:32:16.287	1	7
54	[Task Edited]: ETA Date: Jun 26, 2026, 05:30 AM → Jun 26, 2026, 08:33 AM	2026-06-26 06:42:45.919	1	7
55	[Task Edited]: ETA Date: Jun 26, 2026, 05:30 AM → Jun 26, 2026, 09:34 AM	2026-06-26 06:42:54.923	1	7
56	[Task Edited]: ETA Date: Jun 26, 2026, 05:30 AM → Jun 26, 2026, 10:35 AM	2026-06-26 06:43:04.793	1	7
57	[Task Edited]: ETA Date: Jun 26, 2026, 05:30 AM → Jun 26, 2026, 11:36 PM	2026-06-26 06:43:26.207	1	7
58	[Task Edited]: ETA Date: Jun 26, 2026, 05:30 AM → Jun 26, 2026, 01:30 PM	2026-06-26 06:44:00.034	1	7
59	[Task Edited]: ETA Date: Jun 27, 2026, 05:30 AM → Jun 27, 2026, 05:30 PM	2026-06-26 06:58:09.804	1	7
60	[Task Edited]: ETA Date: Jun 26, 2026, 05:30 AM → Jun 26, 2026, 04:30 PM	2026-06-26 06:58:23.552	1	7
61	[Task Edited]: ETA Date: Jun 26, 2026, 05:30 AM → Jun 26, 2026, 08:30 PM	2026-06-26 06:59:15.48	1	7
62	[Task Edited]: ETA Date: Jun 26, 2026, 05:30 AM → Jun 26, 2026, 07:30 PM	2026-06-26 07:02:52.414	1	7
\.


--
-- Data for Name: task_progress; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_progress (id, created_at, notes, progress_percentage, employee_id, task_id) FROM stdin;
1	2026-06-16 18:58:32.206327		75	3	2
2	2026-06-16 18:58:42.306306		75	3	2
3	2026-06-16 18:59:26.593561		45	3	2
4	2026-06-16 18:59:50.803681		45	3	2
5	2026-06-16 19:05:15.869337		100	3	2
\.


--
-- Data for Name: task_status_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_status_history (id, changed_at, new_status, old_status, reason, changed_by, task_id) FROM stdin;
1	2026-06-16 18:54:45.895018	IN_PROGRESS	OPEN	\N	3	1
2	2026-06-16 18:58:27.175481	IN_PROGRESS	OPEN	\N	3	2
3	2026-06-16 19:04:53.949004	IN_PROGRESS	OPEN	\N	3	3
4	2026-06-16 19:05:26.827933	COMPLETED	IN_PROGRESS	\N	3	2
6	2026-06-18 16:02:09.215437	IN_PROGRESS	OPEN	\N	1	4
9	2026-06-18 16:09:33.053205	IN_PROGRESS	OPEN	\N	1	7
10	2026-06-18 16:21:50.695804	IN_PROGRESS	OPEN	\N	12	11
14	2026-06-18 16:51:05.080495	IN_PROGRESS	OPEN	\N	25	9
15	2026-06-18 16:52:07.054344	IN_PROGRESS	OPEN	\N	16	8
16	2026-06-18 16:54:53.490244	IN_PROGRESS	OPEN	\N	16	10
17	2026-06-22 16:56:17.738316	PENDING_REVIEW	IN_PROGRESS	\N	16	8
18	2026-06-22 17:14:04.058101	COMPLETED	PENDING_REVIEW	\N	25	8
19	2026-06-22 17:14:04.074826	COMPLETED	PENDING_REVIEW	\N	25	8
20	2026-06-25 11:53:11.216206	IN_PROGRESS	OPEN	\N	1	12
21	2026-06-26 11:11:48.651238	PENDING_REVIEW	OPEN	Submitted for completion review	3	6
22	2026-06-26 11:12:31.204319	OVER_ETA	PENDING_REVIEW	Unsubmitted task from completion review	3	6
23	2026-06-26 11:12:35.483516	PENDING_REVIEW	OVER_ETA	Submitted for completion review	3	6
24	2026-06-26 11:15:10.041025	IN_PROGRESS	PENDING_REVIEW	Task completion review: REJECTED. Comment: 	1	6
25	2026-06-26 11:30:49.592862	PENDING_REVIEW	IN_PROGRESS	Submitted for completion review	3	12
26	2026-06-26 11:37:20.598012	PENDING_REVIEW	OPEN	Submitted for completion review	3	5
27	2026-06-26 11:37:22.492443	OVER_ETA	PENDING_REVIEW	Unsubmitted task from completion review	3	5
28	2026-06-26 11:37:37.910022	PENDING_REVIEW	OVER_ETA	Submitted for completion review	3	5
29	2026-06-26 11:37:38.931654	OVER_ETA	PENDING_REVIEW	Unsubmitted task from completion review	3	5
30	2026-06-26 11:37:43.92281	PENDING_REVIEW	OVER_ETA	Submitted for completion review	3	5
31	2026-06-26 11:40:11.636922	COMPLETED	PENDING_REVIEW	Task completion review: APPROVED. Comment: danldskn	1	12
32	2026-06-26 11:40:17.747249	COMPLETED	PENDING_REVIEW	Task completion review: APPROVED. Comment: sndliajdsl	1	5
33	2026-06-26 11:43:51.518864	PENDING_REVIEW	COMPLETED	Undid task completion review decision	1	12
34	2026-06-26 11:43:53.179526	PENDING_REVIEW	COMPLETED	Undid task completion review decision	1	5
35	2026-06-26 11:44:57.300831	COMPLETED	PENDING_REVIEW	Unsubmitted task from completion review	3	12
36	2026-06-26 11:47:32.150179	OVER_ETA	IN_PROGRESS	Task automatically marked OVER_ETA due to hours/date breach	3	6
37	2026-06-26 11:56:47.688165	COMPLETED	PENDING_REVIEW	Unsubmitted task from completion review	3	5
38	2026-06-26 11:58:01.868014	PENDING_REVIEW	OVER_ETA	Undid task completion review decision	1	6
\.


--
-- Data for Name: task_tag_mapping; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_tag_mapping (id, tag_id, task_id) FROM stdin;
\.


--
-- Data for Name: task_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_tags (id, created_at, tag_name) FROM stdin;
\.


--
-- Data for Name: task_transfer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_transfer (id, created_at, reason, rejection_reason, reviewed_at, status, requested_by, reviewed_by, target_employee_id, task_id) FROM stdin;
\.


--
-- Data for Name: tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks (id, created_at, created_by, updated_at, updated_by, delete_reason, deleted_at, deleted_by, is_deleted, bug_number, description, epic, eta_date, eta_hours, extended_eta_date, original_eta_date, priority, status, task_number, task_type, title, assigned_to, project_id, completion_review_status, justification, logged_hours, review_comment) FROM stdin;
7	2026-06-17 16:53:09.32482	1	2026-06-26 12:28:15.493333	1	\N	\N	\N	f	CCS-13588 		Backlog	2026-06-26	8.00	\N	2026-06-25	MEDIUM	IN_PROGRESS	TSK-006	BUG	Bug Fix Implementation and Testing 	12	4	\N	\N	\N	\N
2	2026-06-16 18:57:44.611979	3	2026-06-16 19:05:49.757316	3	"Removed by admin"	2026-06-16 19:05:49.756237	3	t	\N		Backlog	2026-06-17	4.00	\N	2026-06-17	MEDIUM	COMPLETED	1234	TASK	task testing in timesheer	3	3	\N	\N	\N	\N
1	2026-06-16 18:52:16.68007	3	2026-06-17 16:43:39.98812	1	"Removed by admin"	2026-06-17 16:43:39.98181	1	t	\N		Backlog	2026-06-17	4.00	\N	2026-06-17	LOW	IN_PROGRESS	task-0001	TASK	qweqwe	\N	3	\N	\N	\N	\N
3	2026-06-16 18:57:44.635754	3	2026-06-17 16:43:42.905303	1	"Removed by admin"	2026-06-17 16:43:42.905303	1	t	\N		Backlog	2026-06-17	4.00	\N	2026-06-17	MEDIUM	IN_PROGRESS	123	TASK	Testsuadsh	\N	3	\N	\N	\N	\N
13	2026-06-18 17:14:50.002948	1	2026-06-18 17:14:50.002948	1	\N	\N	\N	f	\N	\N	Backlog	2026-06-25	4.00	\N	2026-06-25	MEDIUM	OPEN	CCS-19605	STORY	 SSID Name & Password Error Corrections Across 9 Pages 	\N	7	\N	\N	\N	\N
14	2026-06-18 17:23:24.353878	1	2026-06-18 17:23:24.353878	1	\N	\N	\N	f	\N	\N	Backlog	2026-06-25	8.00	\N	2026-06-25	MEDIUM	OPEN	TASK-009	STORY	CommandIQ & CommandWorx Environment Setup and Package Synchronization 	\N	4	\N	\N	\N	\N
8	2026-06-17 16:53:09.32482	1	2026-06-22 17:14:04.087081	25	\N	\N	\N	f	\N		Backlog	2026-06-18	5.00	\N	2026-06-18	MEDIUM	COMPLETED	TSK-004	TASK	MAC-16 VM Issue – Ticket Created (EOSM-63102) 	16	4	\N	\N	\N	\N
12	2026-06-18 17:12:34.784003	1	2026-06-26 11:44:57.34379	3	\N	\N	\N	f	\N		Backlog	2026-06-19	4.00	\N	2026-06-19	MEDIUM	COMPLETED	(EOSM-63102)	STORY	MAC-16 VM Issue – Ticket Created 	3	7	\N	\N	\N	\N
5	2026-06-17 16:47:16.354257	1	2026-06-26 11:56:47.691171	3	\N	\N	\N	f	\N		Backlog	2026-06-18	3.00	\N	2026-06-18	LOW	COMPLETED	TSK-001	TASK	schedule meeting changes	3	3	\N	\N	\N	\N
6	2026-06-17 16:47:16.357373	1	2026-06-26 11:58:01.871537	1	\N	\N	\N	f	\N		Backlog	2026-06-18	4.00	\N	2026-06-18	MEDIUM	PENDING_REVIEW	TSK-003	STORY	Team attendance fully built along with some major css changes	3	3	\N	jajja	7.00	\N
11	2026-06-17 17:15:38.16414	1	2026-06-26 11:59:58.869489	1	\N	\N	\N	f	\N		Backlog	2026-06-25	2.00	\N	2026-06-18	MEDIUM	IN_PROGRESS	TASK-008	STORY	CommandIQ & Command Worx Environment Setup and Package Synchronization (Latest CommandIQ, Modular-iOS, and UIToolKit Branches) 	12	5	\N	\N	\N	\N
9	2026-06-17 16:53:09.32482	1	2026-06-26 12:00:12.306352	1	\N	\N	\N	f	CCS-19605		Backlog	2026-07-01	8.00	\N	2026-06-26	MEDIUM	IN_PROGRESS	TSK-007	BUG	 Bug Analysis, Fix Implementation & Testing	13	4	\N	\N	\N	\N
4	2026-06-17 16:47:16.354257	1	2026-06-26 12:01:09.240061	1	\N	\N	\N	f	\N		Backlog	2026-07-24	2.00	\N	2026-06-18	MEDIUM	IN_PROGRESS	TSK-002	STORY	Add proper updateemployee when assigned as teamlead and removed unused pages in sidebar	12	3	\N	\N	\N	\N
10	2026-06-17 16:53:09.32482	1	2026-06-26 12:01:13.216158	1	\N	\N	\N	f	CCS-17451		Backlog	2026-07-04	3.00	\N	2026-06-25	MEDIUM	IN_PROGRESS	TSK-005	BUG	Bug Fix Implementation, Rework & Validation	16	4	\N	\N	\N	\N
\.


--
-- Data for Name: team_members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.team_members (id, joined_at, employee_id, team_id) FROM stdin;
11	2026-06-17 15:35:12.154994	16	5
12	2026-06-17 15:35:12.177532	12	5
13	2026-06-17 15:35:12.19607	15	5
14	2026-06-17 15:35:12.215629	13	5
15	2026-06-17 15:37:10.695629	14	6
17	2026-06-17 15:37:10.752667	16	6
18	2026-06-17 15:37:10.772025	17	6
19	2026-06-17 16:26:13.422687	24	7
20	2026-06-17 16:26:13.452679	17	7
21	2026-06-17 16:26:13.47999	15	7
22	2026-06-17 16:26:13.502987	16	7
23	2026-06-17 16:26:13.529828	14	7
24	2026-06-17 16:26:13.553594	12	7
25	2026-06-17 16:26:13.578961	13	7
26	2026-06-18 12:57:14.000487	1	10
27	2026-06-18 12:57:14.025734	12	10
28	2026-06-18 12:57:14.052596	16	10
29	2026-06-18 12:57:14.087065	14	10
\.


--
-- Data for Name: teams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teams (id, created_at, created_by, updated_at, updated_by, delete_reason, deleted_at, deleted_by, is_deleted, description, status, team_name, teams_channel_id, lead_id, sub_lead_id) FROM stdin;
2	2026-06-17 11:27:42.631668	1	2026-06-17 13:21:51.679053	1	"Removed by admin"	2026-06-17 13:21:51.679053	1	t		INACTIVE	TESTING		6	5
3	2026-06-17 11:34:36.55508	1	2026-06-17 15:09:30.562078	1	"Removed by admin"	2026-06-17 15:09:30.562078	1	t	qwe123	INACTIVE	tiithshs		1	2
4	2026-06-17 11:55:41.652461	6	2026-06-17 15:09:38.479791	1	"Removed by admin"	2026-06-17 15:09:38.479186	1	t	wqe	INACTIVE	w123		1	2
1	2026-06-16 18:35:08.682479	3	2026-06-17 15:11:39.973507	1	"Removed by admin"	2026-06-17 15:11:39.973507	1	t	Elite Resource Management	INACTIVE	Resource Management		1	2
6	2026-06-17 15:37:10.640126	1	2026-06-17 15:37:10.640126	1	\N	\N	\N	f		ACTIVE	IOS Team (Mobile App)		14	\N
7	2026-06-17 16:26:13.350261	1	2026-06-17 16:26:13.350261	1	\N	\N	\N	f		ACTIVE	Calix		24	\N
8	2026-06-18 12:47:27.777466	16	2026-06-18 12:47:27.777466	16	\N	\N	\N	f		ACTIVE	qwertyui		1	12
10	2026-06-18 12:57:13.931352	16	2026-06-18 12:57:51.551028	16	\N	\N	\N	f	suck	ACTIVE	ligma		5	1
5	2026-06-17 15:35:12.068532	1	2026-06-18 13:01:14.801234	16	\N	\N	\N	f	Test	ACTIVE	AAM Web APP		16	12
\.


--
-- Data for Name: timesheet_entries; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.timesheet_entries (id, approved_at, bug_number, created_at, description, end_time, hours_spent, justification, manager_comment, start_time, status, work_category, work_date, approved_by, employee_id, project_id, task_id) FROM stdin;
1	\N	\N	2026-06-23 16:48:26.983888	Lunch break	2026-06-23 11:30:00	0.50	\N	\N	2026-06-23 11:00:00	PENDING	BREAK	2026-06-23	\N	1	\N	\N
2	\N	\N	2026-06-23 17:46:58.676928	Break	2026-06-23 13:00:00	4.00		\N	2026-06-23 09:00:00	PENDING	BREAK	2026-06-23	\N	3	\N	\N
3	2026-06-26 11:14:30.435723	\N	2026-06-23 18:02:33.490326	eq	2026-06-17 13:00:00	4.00			2026-06-17 09:00:00	APPROVED	STORY	2026-06-17	1	3	3	6
4	\N	\N	2026-06-26 11:47:32.092751	alds n	2026-06-26 10:00:00	1.00	dasds	\N	2026-06-26 09:00:00	APPROVED	STORY	2026-06-26	\N	3	3	6
5	\N	\N	2026-06-26 11:48:19.948924	asd	2026-06-26 14:00:00	2.00	sdasd	\N	2026-06-26 12:00:00	APPROVED	STORY	2026-06-26	\N	3	3	6
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (id, assigned_at, assigned_by, role_id, user_id) FROM stdin;
1	2026-06-16 18:09:37.759221	\N	1	1
2	2026-06-16 18:09:37.886458	\N	4	2
4	2026-06-16 18:14:45.321541	1	2	4
11	2026-06-17 11:34:36.635283	1	2	7
19	2026-06-17 13:27:08.836578	1	4	6
20	2026-06-17 14:48:40.325326	1	4	8
21	2026-06-17 14:49:05.336928	1	4	9
22	2026-06-17 14:49:29.429098	1	4	10
26	2026-06-17 15:20:47.039838	1	4	13
28	2026-06-17 15:25:53.092815	1	4	15
30	2026-06-17 15:28:34.835006	1	4	17
31	2026-06-17 15:35:12.137561	1	2	16
32	2026-06-17 15:37:10.674666	1	2	14
33	2026-06-17 16:12:59.765741	1	4	20
34	2026-06-17 16:13:19.613572	1	1	21
35	2026-06-17 16:24:57.080404	1	1	25
36	2026-06-17 16:39:18.783096	1	4	3
37	2026-06-17 16:39:55.162204	1	4	5
38	2026-06-17 16:40:33.912528	1	4	26
41	2026-06-18 12:47:27.822528	\N	2	1
43	2026-06-18 12:57:13.976276	\N	3	1
44	2026-06-18 12:57:51.556826	\N	2	5
45	2026-06-18 16:09:58.289919	1	2	27
51	2026-06-18 16:23:22.509364	25	3	12
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, account_locked_until, created_at, email, failed_login_attempts, force_password_change, is_active, last_login, password_hash, password_last_updated_at, updated_at) FROM stdin;
4	\N	2026-06-16 18:14:45.31499	aki@gmail.com	0	f	f	\N	$2a$10$hYMnWd5iUnl0w49VEepBL.6yCIYq3QYyHwNDPYKR6SCw3xtmmapfy	2026-06-16 18:14:45.31499	2026-06-16 18:14:45.31499
12	\N	2026-06-17 15:19:47.137226	yogeshwaran@elitecorpusa.com	0	f	t	2026-06-18 16:23:33.805488	$2a$10$LduqY9saUeqbS5Njr6inWOpavDUi8Cver0eepel0R6fLpU6mbceWC	2026-06-18 16:23:22.504115	2026-06-17 15:19:47.137226
7	\N	2026-06-17 11:27:02.169563	rithvasdasdikradhika@gmail.com	0	f	f	2026-06-17 14:47:16.745328	$2a$10$XwRBCIwSNkwbFwQgBLsczeweVcg4xvooD304n1N4ovZ7FecX8fSre	2026-06-17 11:30:55.189901	2026-06-17 11:27:02.169563
6	\N	2026-06-16 18:16:55.928907	ritasdesh@gmail.com	0	f	f	2026-06-17 14:46:58.237894	$2a$10$Jh70A9veZpRYBlDifp/dyudUToYHPo9lD4Ni6dQfW7rxFIA2axpW.	2026-06-17 13:27:08.831676	2026-06-16 18:16:55.928907
8	\N	2026-06-17 14:48:40.31867	emp@emp.com	0	f	f	\N	$2a$10$YGEP.WOYuy3TjGY1FMeuyewBclS/t6d7mHTnLcqSNNo8PqPcW3/dK	2026-06-17 14:48:40.31867	2026-06-17 14:48:40.31867
9	\N	2026-06-17 14:49:05.332812	emp2@emp.com	0	f	f	\N	$2a$10$PZQneqihmhbt8AaDX5wPnunSy9zSrheWbQmTSSw9zyfokH3/uaxVS	2026-06-17 14:49:05.332812	2026-06-17 14:49:05.332812
10	\N	2026-06-17 14:49:29.425614	emp3@emp.com	0	f	f	\N	$2a$10$5PIFhDPU.FGgl49wtJbAdePLW8Uu4U19yCZq.cCey8tNpf/AjP87S	2026-06-17 14:49:29.425614	2026-06-17 14:49:29.425614
2	\N	2026-06-16 18:09:37.879299	employee@teamops.com	0	f	f	\N	$2a$10$sbZC7BZmfw/qL/.Xn.yKdOkAQHYxV6vzenXEbhyWyg7UHLUNaX9wC	2026-06-16 18:09:37.879299	2026-06-16 18:09:37.879299
14	\N	2026-06-17 15:25:08.568479	MDIqbalA@elitecorpusa.com	0	f	t	\N	$2a$10$x2Y7NcS6.lVTrSOzw1oot.2vq0Hn/yhhBxyHGudWSkjtXWpmLp68.	2026-06-17 15:25:08.568479	2026-06-17 15:25:08.568479
15	\N	2026-06-17 15:25:53.086762	JeganRajendran@elitecorpusa.com	0	f	t	\N	$2a$10$3RI61L3AqE7ZaiRWMwcpBe/GkF9PvoZqUUfkp2B2EOyOW0shWVYcC	2026-06-17 15:25:53.086762	2026-06-17 15:25:53.086762
17	\N	2026-06-17 15:28:34.832276	BalamuruganRavi@elitecorpusa.com	0	f	t	2026-06-18 16:46:47.393068	$2a$10$VlcaYH5ptz27K4Gnl/jX..XF1CjmOxwATviH2uLhExpC3bBRiQ/GC	2026-06-17 15:28:34.832276	2026-06-17 15:28:34.832276
16	\N	2026-06-17 15:27:05.96451	RichardMathew@elitecorpusa.com	0	f	t	2026-06-22 17:11:54.186658	$2a$10$SicN0247E/8nmZ41TU/Zb.n/GGwmdsP04wLPjTizUEm7gcgPN3E42	2026-06-17 15:27:05.96451	2026-06-17 15:27:05.96451
20	\N	2026-06-17 16:12:59.760625	admin@teamops.comqweqw	0	f	f	\N	$2a$10$M0WIO.m./qBH5LeNZxQmSO//2fcCsp9P.TqHpFdtHqDYihuExdo8G	2026-06-17 16:12:59.760625	2026-06-17 16:12:59.760625
21	\N	2026-06-17 16:13:19.608342	admin@teamops.comasdqwe	0	f	f	\N	$2a$10$ze7XkRSaRr/dGoDBfLKReOOL2nVZoZnkRXnku0IUFdgGuymEWpzeK	2026-06-17 16:13:19.608342	2026-06-17 16:13:19.608342
25	\N	2026-06-17 16:24:57.076384	spurushothaman@elitecorpusa.com	0	f	t	2026-06-22 17:13:19.740378	$2a$10$Pp9D6SAG2UOfnKS3EZrwheWSNgAY7NpQwESi2xkufUNhxAGwY/QXi	2026-06-17 16:24:57.076384	2026-06-17 16:24:57.076384
27	\N	2026-06-18 12:21:47.198488	wqert@qwe.com	0	f	t	2026-06-18 12:22:19.467133	$2a$10$L08jYeszugAmEWJjEHLhi.8cA9GpRi9whqR/a/zF2GxERZEZQymEq	2026-06-18 12:22:15.350137	2026-06-18 12:21:47.198488
5	\N	2026-06-16 18:16:01.069777	ritesh@gmail.com	0	f	t	2026-06-24 12:13:43.794803	$2a$10$d/ac88H4dHIxiIUBzX/jveI/duJMV4Vy7xq59XxmXvBJIfFXzl42G	2026-06-17 16:39:55.159079	2026-06-16 18:16:01.069777
13	\N	2026-06-17 15:20:37.15853	Karuppasamy@elitecorpusa.com	0	f	t	2026-06-18 16:55:06.546199	$2a$10$qWpALyiM3j0QQi.1s4Hw/.qi5rndXBwUetXhKPPsYzDAs45cJHhVC	2026-06-17 15:20:47.036709	2026-06-17 15:20:37.15853
3	\N	2026-06-16 18:13:44.969641	rithvikradhika@gmail.com	0	f	t	2026-06-26 11:56:18.378901	$2a$10$Sx0Bik.v.Ix1Ozz5oTDbTep0k/TY4W7YMbxn2fRNGa4Zs7VNAO5Em	2026-06-17 16:39:18.777375	2026-06-16 18:13:44.969641
26	\N	2026-06-17 16:40:33.909374	Akhilesh@gmail.com	0	f	t	2026-06-23 16:43:43.41137	$2a$10$AvMSa9.BCFSCEoQHx8VJH.hCMwYCxMHcZtwdDock2dFeGbtydEuCG	2026-06-17 16:40:33.909374	2026-06-17 16:40:33.909374
1	\N	2026-06-16 18:09:37.752397	admin@teamops.com	0	f	t	2026-06-26 15:38:52.258184	$2a$10$3Nbl1rE63//o3u82Dbc2G.f74o3lfy2Z1MPHbEQB7dffVc/0rHYqO	2026-06-16 18:09:37.752397	2026-06-16 18:09:37.752397
\.


--
-- Name: attachments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attachments_id_seq', 1, false);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.audit_logs_id_seq', 1, false);


--
-- Name: components_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.components_id_seq', 5, true);


--
-- Name: employees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employees_id_seq', 26, true);


--
-- Name: eta_extension_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.eta_extension_requests_id_seq', 1, true);


--
-- Name: feed_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.feed_id_seq', 1, true);


--
-- Name: links_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.links_id_seq', 1, true);


--
-- Name: meetings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.meetings_id_seq', 1, false);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.password_reset_tokens_id_seq', 1, false);


--
-- Name: permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permissions_id_seq', 46, true);


--
-- Name: project_members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.project_members_id_seq', 41, true);


--
-- Name: project_milestones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.project_milestones_id_seq', 1, false);


--
-- Name: project_teams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.project_teams_id_seq', 1, false);


--
-- Name: projects_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.projects_id_seq', 8, true);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_tokens_id_seq', 12, true);


--
-- Name: role_components_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_components_id_seq', 11, true);


--
-- Name: role_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_permissions_id_seq', 139, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 4, true);


--
-- Name: task_attachments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_attachments_id_seq', 1, false);


--
-- Name: task_comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_comments_id_seq', 62, true);


--
-- Name: task_progress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_progress_id_seq', 5, true);


--
-- Name: task_status_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_status_history_id_seq', 38, true);


--
-- Name: task_tag_mapping_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_tag_mapping_id_seq', 1, false);


--
-- Name: task_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_tags_id_seq', 1, false);


--
-- Name: task_transfer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_transfer_id_seq', 1, false);


--
-- Name: tasks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_id_seq', 14, true);


--
-- Name: team_members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.team_members_id_seq', 29, true);


--
-- Name: teams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teams_id_seq', 10, true);


--
-- Name: timesheet_entries_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.timesheet_entries_id_seq', 5, true);


--
-- Name: user_roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_roles_id_seq', 51, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 27, true);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: components components_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.components
    ADD CONSTRAINT components_pkey PRIMARY KEY (id);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: eta_extension_requests eta_extension_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eta_extension_requests
    ADD CONSTRAINT eta_extension_requests_pkey PRIMARY KEY (id);


--
-- Name: feed feed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feed
    ADD CONSTRAINT feed_pkey PRIMARY KEY (id);


--
-- Name: links links_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_pkey PRIMARY KEY (id);


--
-- Name: meeting_attendees meeting_attendees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_attendees
    ADD CONSTRAINT meeting_attendees_pkey PRIMARY KEY (meeting_id, employee_id);


--
-- Name: meetings meetings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- Name: project_members project_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT project_members_pkey PRIMARY KEY (id);


--
-- Name: project_milestones project_milestones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_milestones
    ADD CONSTRAINT project_milestones_pkey PRIMARY KEY (id);


--
-- Name: project_teams project_teams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_teams
    ADD CONSTRAINT project_teams_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: role_components role_components_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_components
    ADD CONSTRAINT role_components_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: task_attachments task_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_attachments
    ADD CONSTRAINT task_attachments_pkey PRIMARY KEY (id);


--
-- Name: task_comments task_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_comments
    ADD CONSTRAINT task_comments_pkey PRIMARY KEY (id);


--
-- Name: task_progress task_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_progress
    ADD CONSTRAINT task_progress_pkey PRIMARY KEY (id);


--
-- Name: task_status_history task_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_status_history
    ADD CONSTRAINT task_status_history_pkey PRIMARY KEY (id);


--
-- Name: task_tag_mapping task_tag_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_tag_mapping
    ADD CONSTRAINT task_tag_mapping_pkey PRIMARY KEY (id);


--
-- Name: task_tags task_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_tags
    ADD CONSTRAINT task_tags_pkey PRIMARY KEY (id);


--
-- Name: task_transfer task_transfer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_transfer
    ADD CONSTRAINT task_transfer_pkey PRIMARY KEY (id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- Name: team_members team_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT team_members_pkey PRIMARY KEY (id);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: timesheet_entries timesheet_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timesheet_entries
    ADD CONSTRAINT timesheet_entries_pkey PRIMARY KEY (id);


--
-- Name: components uk1yeg2ib697ws6b8n6ddymeqkx; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.components
    ADD CONSTRAINT uk1yeg2ib697ws6b8n6ddymeqkx UNIQUE (component_key);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: roles uk949pwsnk7kxk0px0tbj3r3web; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uk949pwsnk7kxk0px0tbj3r3web UNIQUE (role_code);


--
-- Name: user_roles uka9dydk3dj4qb8cvmjijqnrg5t; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT uka9dydk3dj4qb8cvmjijqnrg5t UNIQUE (user_id, role_id);


--
-- Name: project_members ukap080b24p4j7yfv3ww9gamt5u; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT ukap080b24p4j7yfv3ww9gamt5u UNIQUE (project_id, employee_id);


--
-- Name: task_tag_mapping ukeams4002rxxbglfoxv1jjix1y; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_tag_mapping
    ADD CONSTRAINT ukeams4002rxxbglfoxv1jjix1y UNIQUE (task_id, tag_id);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: team_members ukgwiekr3b4g6uu8h3v5q03jqxy; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT ukgwiekr3b4g6uu8h3v5q03jqxy UNIQUE (team_id, employee_id);


--
-- Name: task_tags ukkrc7li8lprmh7q9n3kk8iarr4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_tags
    ADD CONSTRAINT ukkrc7li8lprmh7q9n3kk8iarr4 UNIQUE (tag_name);


--
-- Name: permissions uknry1f3jmc4abb5yvkftlvn6vg; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT uknry1f3jmc4abb5yvkftlvn6vg UNIQUE (permission_name);


--
-- Name: project_teams ukpl6vnxfj9hgq5b29u820cj5bp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_teams
    ADD CONSTRAINT ukpl6vnxfj9hgq5b29u820cj5bp UNIQUE (project_id, team_id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_employees_code_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_employees_code_active ON public.employees USING btree (employee_code) WHERE (is_deleted = false);


--
-- Name: idx_employees_phone_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_employees_phone_active ON public.employees USING btree (phone) WHERE (is_deleted = false);


--
-- Name: idx_employees_user_id_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_employees_user_id_active ON public.employees USING btree (user_id) WHERE (is_deleted = false);


--
-- Name: idx_employees_work_email_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_employees_work_email_active ON public.employees USING btree (work_email) WHERE (is_deleted = false);


--
-- Name: idx_tasks_task_number; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_tasks_task_number ON public.tasks USING btree (task_number) WHERE (is_deleted = false);


--
-- Name: idx_teams_name_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_teams_name_active ON public.teams USING btree (team_name) WHERE (is_deleted = false);


--
-- Name: idx_users_email_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_users_email_active ON public.users USING btree (email) WHERE (is_active = true);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: timesheet_entries fk1pxpdsc63vdwitawvpypvcc88; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timesheet_entries
    ADD CONSTRAINT fk1pxpdsc63vdwitawvpypvcc88 FOREIGN KEY (approved_by) REFERENCES public.employees(id);


--
-- Name: timesheet_entries fk24hwqv008kc2do8bv2xjaqhn6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timesheet_entries
    ADD CONSTRAINT fk24hwqv008kc2do8bv2xjaqhn6 FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: task_attachments fk4eyiisq4wyx2mfj3p9h8ppufo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_attachments
    ADD CONSTRAINT fk4eyiisq4wyx2mfj3p9h8ppufo FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;


--
-- Name: task_transfer fk678kxbunmpia75po1yml9t876; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_transfer
    ADD CONSTRAINT fk678kxbunmpia75po1yml9t876 FOREIGN KEY (requested_by) REFERENCES public.employees(id) ON DELETE RESTRICT;


--
-- Name: task_transfer fk69551g4kt7hmhdbnx620n3vde; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_transfer
    ADD CONSTRAINT fk69551g4kt7hmhdbnx620n3vde FOREIGN KEY (reviewed_by) REFERENCES public.users(id);


--
-- Name: employees fk69x3vjuy1t5p18a5llb8h2fjx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk69x3vjuy1t5p18a5llb8h2fjx FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: project_members fk6hb0s9g0u21ta4s0bkrghncce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT fk6hb0s9g0u21ta4s0bkrghncce FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- Name: meeting_attendees fk6r5ve3c58rcqqgmcut59m2w12; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_attendees
    ADD CONSTRAINT fk6r5ve3c58rcqqgmcut59m2w12 FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: task_comments fk9517viwn2geh1gpivj6l9y64u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_comments
    ADD CONSTRAINT fk9517viwn2geh1gpivj6l9y64u FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;


--
-- Name: timesheet_entries fk9b4mie5i1xq36af6a87iucp5t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timesheet_entries
    ADD CONSTRAINT fk9b4mie5i1xq36af6a87iucp5t FOREIGN KEY (project_id) REFERENCES public.projects(id);


--
-- Name: eta_extension_requests fk9h50x0s7plhpebmaocn8fb48n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eta_extension_requests
    ADD CONSTRAINT fk9h50x0s7plhpebmaocn8fb48n FOREIGN KEY (requested_by) REFERENCES public.employees(id) ON DELETE RESTRICT;


--
-- Name: eta_extension_requests fka1ygfbm0ipc6sl0951os5kj67; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eta_extension_requests
    ADD CONSTRAINT fka1ygfbm0ipc6sl0951os5kj67 FOREIGN KEY (reviewed_by) REFERENCES public.users(id);


--
-- Name: components fkadn61cam58x5g7ikj431o7pvv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.components
    ADD CONSTRAINT fkadn61cam58x5g7ikj431o7pvv FOREIGN KEY (parent_component_id) REFERENCES public.components(id);


--
-- Name: task_tag_mapping fkapx5cw26k6ttm99d0ovykyaew; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_tag_mapping
    ADD CONSTRAINT fkapx5cw26k6ttm99d0ovykyaew FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;


--
-- Name: role_components fkb0xhpfnvp6tgwnn9nbr9pje69; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_components
    ADD CONSTRAINT fkb0xhpfnvp6tgwnn9nbr9pje69 FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- Name: meetings fkbt3vmcde0efob60esnfkyaeg0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT fkbt3vmcde0efob60esnfkyaeg0 FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;


--
-- Name: project_teams fkbuiohfur09u2n2isrusu0upw9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_teams
    ADD CONSTRAINT fkbuiohfur09u2n2isrusu0upw9 FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: tasks fkc2y22d6enhsanvjek24wis1ly; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fkc2y22d6enhsanvjek24wis1ly FOREIGN KEY (assigned_to) REFERENCES public.employees(id) ON DELETE SET NULL;


--
-- Name: project_members fkdki1sp2homqsdcvqm9yrix31g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT fkdki1sp2homqsdcvqm9yrix31g FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: role_permissions fkegdk29eiy7mdtefy5c7eirr6e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkegdk29eiy7mdtefy5c7eirr6e FOREIGN KEY (permission_id) REFERENCES public.permissions(id) ON DELETE CASCADE;


--
-- Name: task_progress fkej7u63um1fm8c5xfy92125ibm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_progress
    ADD CONSTRAINT fkej7u63um1fm8c5xfy92125ibm FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;


--
-- Name: task_transfer fkejk6orbiy4b92c12j138h98ma; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_transfer
    ADD CONSTRAINT fkejk6orbiy4b92c12j138h98ma FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;


--
-- Name: project_milestones fkf89i5mou2qk96lrjgb8of4mdq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_milestones
    ADD CONSTRAINT fkf89i5mou2qk96lrjgb8of4mdq FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: teams fkgaf0kp4ffdqi3bg6rl4wu3obc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT fkgaf0kp4ffdqi3bg6rl4wu3obc FOREIGN KEY (sub_lead_id) REFERENCES public.employees(id) ON DELETE SET NULL;


--
-- Name: task_tag_mapping fkglo5r4s5u6msy3rw1y0p35j4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_tag_mapping
    ADD CONSTRAINT fkglo5r4s5u6msy3rw1y0p35j4 FOREIGN KEY (tag_id) REFERENCES public.task_tags(id) ON DELETE CASCADE;


--
-- Name: task_progress fkh139yifj1ow278j9if6m0uwwl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_progress
    ADD CONSTRAINT fkh139yifj1ow278j9if6m0uwwl FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE RESTRICT;


--
-- Name: task_attachments fkh2muwbryhtafff6h0tx0xb5pk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_attachments
    ADD CONSTRAINT fkh2muwbryhtafff6h0tx0xb5pk FOREIGN KEY (uploaded_by) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE RESTRICT;


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: task_status_history fkhjg5v31h2idsrbqqorbos4cjw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_status_history
    ADD CONSTRAINT fkhjg5v31h2idsrbqqorbos4cjw FOREIGN KEY (changed_by) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: timesheet_entries fkhvbm8ag76418tcw05k5lbiin2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timesheet_entries
    ADD CONSTRAINT fkhvbm8ag76418tcw05k5lbiin2 FOREIGN KEY (task_id) REFERENCES public.tasks(id);


--
-- Name: task_comments fkie7k1ng04dc2afiayja04i03u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_comments
    ADD CONSTRAINT fkie7k1ng04dc2afiayja04i03u FOREIGN KEY (author_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- Name: team_members fkjdu9hq2eq8ucq5tjhwpunxvt5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT fkjdu9hq2eq8ucq5tjhwpunxvt5 FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- Name: teams fkjeq4ukbaskncspapim1imyrm1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT fkjeq4ukbaskncspapim1imyrm1 FOREIGN KEY (lead_id) REFERENCES public.employees(id) ON DELETE RESTRICT;


--
-- Name: meeting_attendees fkjrrh506w4qj7m1kap6fup86ni; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_attendees
    ADD CONSTRAINT fkjrrh506w4qj7m1kap6fup86ni FOREIGN KEY (meeting_id) REFERENCES public.meetings(id);


--
-- Name: audit_logs fkjs4iimve3y0xssbtve5ysyef0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fkjs4iimve3y0xssbtve5ysyef0 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: eta_extension_requests fkkfxyekwdcwiokliw9hip4vkqa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eta_extension_requests
    ADD CONSTRAINT fkkfxyekwdcwiokliw9hip4vkqa FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;


--
-- Name: task_status_history fklbsvojobaaf8bkuddoe7ig25s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_status_history
    ADD CONSTRAINT fklbsvojobaaf8bkuddoe7ig25s FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;


--
-- Name: user_roles fkljgw07fam7v71ok817u4rvyro; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkljgw07fam7v71ok817u4rvyro FOREIGN KEY (assigned_by) REFERENCES public.users(id);


--
-- Name: meetings fkn1d7fbs7fq4uh60o0wl9c1svx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT fkn1d7fbs7fq4uh60o0wl9c1svx FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE SET NULL;


--
-- Name: role_permissions fkn5fotdgk8d1xvo8nav9uv3muc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkn5fotdgk8d1xvo8nav9uv3muc FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- Name: attachments fko77y9p334n5ni7g16jrrh3042; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT fko77y9p334n5ni7g16jrrh3042 FOREIGN KEY (uploaded_by) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- Name: project_teams fkopcni5f7bojg5cdklmurabyms; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_teams
    ADD CONSTRAINT fkopcni5f7bojg5cdklmurabyms FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- Name: feed fkqhhvbhfkpnfi7q2g4dsv6i7qy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feed
    ADD CONSTRAINT fkqhhvbhfkpnfi7q2g4dsv6i7qy FOREIGN KEY (created_by) REFERENCES public.employees(id);


--
-- Name: role_components fks0eiwxxqw5fpxbqq5t3pve2i0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_components
    ADD CONSTRAINT fks0eiwxxqw5fpxbqq5t3pve2i0 FOREIGN KEY (component_id) REFERENCES public.components(id) ON DELETE CASCADE;


--
-- Name: attachments fks24h44dbmvras7arl5i8sq0dx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT fks24h44dbmvras7arl5i8sq0dx FOREIGN KEY (meeting_id) REFERENCES public.meetings(id) ON DELETE CASCADE;


--
-- Name: tasks fksfhn82y57i3k9uxww1s007acc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fksfhn82y57i3k9uxww1s007acc FOREIGN KEY (project_id) REFERENCES public.projects(id);


--
-- Name: task_transfer fktd9xody9nkuhs8okdtcgiyn8q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_transfer
    ADD CONSTRAINT fktd9xody9nkuhs8okdtcgiyn8q FOREIGN KEY (target_employee_id) REFERENCES public.employees(id) ON DELETE RESTRICT;


--
-- Name: team_members fktgca08el3ofisywcf11f0f76t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT fktgca08el3ofisywcf11f0f76t FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict WMyHwOKUUjVjRaiBxWR4TXlcRChzgaKoabbSlSe81zwDDlbUuzmpsojgZljfpfa

