export const Data = [
  {
    staffMember: "Sarah Jenkins",
    employeeId: "EMP-0001",
    designation: "Management",
    workEmail: "sarah.j@office.com",
    personalEmail: "-",
    phone: "+91 98765 43210",
    activeTasks: "1 task",
    role: "Admin",
    status: "Active",
  },
  {
    staffMember: "Alex Rivera",
    employeeId: "EMP-0002",
    designation: "Engineering",
    workEmail: "alex.r@office.com",
    personalEmail: "-",
    phone: "+91 98765 43211",
    activeTasks: "1 task",
    role: "Team Lead",
    status: "Active",
  },
  {
    staffMember: "Vikram Mehta",
    employeeId: "EMP-0003",
    designation: "Engineering",
    workEmail: "vikram.m@office.com",
    personalEmail: "-",
    phone: "+91 98765 43212",
    activeTasks: "1 task",
    role: "Team Lead",
    status: "Active",
  },
  {
    staffMember: "Marcus Chen",
    employeeId: "EMP-0042",
    designation: "Engineering",
    workEmail: "marcus.c@office.com",
    personalEmail: "-",
    phone: "+91 98765 43213",
    activeTasks: "2 tasks",
    role: "Employee",
    status: "Active",
  },
  {
    staffMember: "Elena Rostova",
    employeeId: "EMP-0043",
    designation: "Design",
    workEmail: "elena.r@office.com",
    personalEmail: "-",
    phone: "+91 98765 43214",
    activeTasks: "3 tasks",
    role: "Employee",
    status: "Active",
  },
  {
    staffMember: "Liam O'Connor",
    employeeId: "EMP-0044",
    designation: "Quality Assurance",
    workEmail: "liam.o@office.com",
    personalEmail: "-",
    phone: "+91 98765 43215",
    activeTasks: "1 task",
    role: "Employee",
    status: "Active",
  },
  {
    staffMember: "David Miller",
    employeeId: "EMP-0045",
    designation: "Engineering",
    workEmail: "david.m@office.com",
    personalEmail: "-",
    phone: "+91 98765 43216",
    activeTasks: "3 tasks",
    role: "Employee",
    status: "Active",
  },
];